make BaseIE private
prevents the plugin thing from trying to load it as an extractor
error this prevents:
Traceback (most recent call last):
  File "/home/g/Downloads/yt-dlp/test/test_download.py", line 160, in test_template
    res_dict = ydl.extract_info(
  File "/home/g/Downloads/yt-dlp/yt_dlp/YoutubeDL.py", line 1508, in extract_info
    if not ie.suitable(url):
  File "/home/g/Downloads/yt-dlp/yt_dlp/extractor/common.py", line 563, in suitable
    return cls._match_valid_url(url) is not None
  File "/home/g/Downloads/yt-dlp/yt_dlp/extractor/common.py", line 555, in _match_valid_url
    cls._VALID_URL_RE = re.compile(cls._VALID_URL)
  File "/usr/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.10/re.py", line 302, in _compile
    raise TypeError("first argument must be string or compiled pattern")
TypeError: first argument must be string or compiled pattern

(BaseIE doesnt have _VALID_URL, so it fails. If I add one, it wants a _real_extract)